### ISSUE TITLE
Autogen package list is broken

### ISSUE THREAD

**Issue by wildintellect** [stactools-packages/stactools-packages.github.io#7]
The table of existing packages doesn't seem to be working. Have not looked into the root cause yet.

**Comment by gadomski** [comment]
What's broken about it? It says it was updated today.

![image](https://user-images.githubusercontent.com/58314/221889114-ae018527-96f5-4573-adf5-9877f1be2c80.png)

**Comment by wildintellect** [comment]
Odd I should have taken a screenshot yesterday, the table was empty when I loaded it. Seems to be working now.
